### ISSUE TITLE
02 - 02 C# Iteration - Working with LINQ

### ISSUE THREAD

**Issue by piercebhunt** [piercebhunt/assignments#5]
Learning programming takes practice and the best practice is repetition. This
exercise will allow you time to work on the basics of .NET and how to apply that
logic to solving problems.

## Objectives

After completing this assignment, you should be able to:

- Demonstrate understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/net-iteration) to
   your own account.
2. Change into your projects directory:
3. Clone your repository:
   `git clone https://github.com/YOUR_NAME_HERE/net-iteration`
4. Change into your project's directory: `cd net-iteration`
5. Install the dependencies: `dotnet restore`
6. Open in your editor: `code .`
7. Start the test runner: `dotnet watch test`
8. Open `Iterations.cs` and work on functions until the test passes. Once you
   are done with a test you can move to the next one by removing the
   `(Skip = "Remove to run test")` from the `Fact` attribute. There are a total
   of 10 questions.
9. Commit and push your work to GitHub.
10. Turn in the URL to your GitHub repo.

## Explorer Mode

- All tests passing
- No linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Additional Resources

Reference the documentation to find what kind of helpful functions
might already be in C#.

- [String Functions](https://www.c-sharpcorner.com/blogs/some-string-functions-of-c-sharp).
- [Official LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/)

**Comment by piercebhunt** [comment]
https://github.com/huntpie/net-iteration

**Comment by piercebhunt** [comment]
Your homework **02 - 02 C# Iteration - Working with LINQ** was marked: **Acceptable**

![Not Bad](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26e47afe0d88e75d27a696b1e3719f5c026a93c5/not-bad.gif)
> &ldquo;Not Bad&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/6)**__

**Comment by gstark** [comment]
Pierce, I am going to accept this homework since it does show you are understanding the information. I will challenge you to go back to this assignment in a week or so and see if you can complete it again with the recommendations I make below.

Good work!


You can remove this line [here](https://github.com/huntpie/net-iteration/blob/master/Iterations.cs#L51)

You can use string interpolation [here](https://github.com/huntpie/net-iteration/blob/master/Iterations.cs#L67-L68)

```
        var suffixedElement = $"{item} is at index {index}";
```

See if you can do [this one](https://github.com/huntpie/net-iteration/blob/master/Iterations.cs#L87-L99) without building a new list.

Nicely done, but can you do [this one](https://github.com/huntpie/net-iteration/blob/master/Iterations.cs#L140-L148) without building a new list.

Any time we have code [like this](https://github.com/huntpie/net-iteration/blob/master/Iterations.cs#L164-L171) where it fits the pattern

```
if (condition)
{
   return true;
}
else
{
  return false;
}
```

we can just write

```
return condition;
```

So this becomes
```
    public static bool EveryoneIsOdd(List<int> data)
    {
      return (data.TrueForAll(x => x % 2 != 0));
    }
```

Can you also [do this](https://github.com/huntpie/net-iteration/blob/master/Iterations.cs#L185-L192) without `foreach`
